version: '3'
services:
  solr4:
    restart: always
    image: reflet/docker-solr4:1.2
    container_name: 'solr4'
    ports:
     - "8983:8983"
    volumes:
      - solr4-data:/usr/solr/solr-4.7.2/server/multicore/
      - solr4-logs:/usr/solr/solr-4.7.2/logs/
volumes:
  solr4-data:
    driver: local
  solr4-logs:
    driver: local

