version: '3'
services:
  solr4:
    restart: always
    build: .
    container_name: 'solr4'
    ports:
     - "8004:8983"
    volumes:
      - solr4-data:/usr/solr/solr-4.7.2/server/multicore/
      - solr4-logs:/usr/solr/solr-4.7.2/logs/
volumes:
  solr4-data:
    driver: local
  solr4-logs:
    driver: local
